# NUMPY



# What is NumPy?
Numerical Python

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why Use NumPy?

Python Lists are slow.

Numpy array is an object(ndarray), 50X faster than lists


# Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## Installing Numpy

In [50]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## import numpy

In [51]:
import numpy as np

## check numpy version

In [52]:
np.__version__

'1.24.3'

### array() - used to create an nd array object 
### type()- used to check type of object passed in a function
### we can pass list or tuple and this will be converted to nd array

In [56]:
arr = np.array([23,34,34])
arr2 = np.array((54,45,34))
# print(arr)
print(arr2)

[54 45 34]


In [57]:
type(arr2)

numpy.ndarray

In [59]:
type(arr)

numpy.ndarray

## Dimensions in array

dimension - one level of array depth

0d - 0 dimensional
1d - 1 dimensional
2d - 2 dimensional

In [62]:
zerod = np.array(34)
zerod

array(34)

In [68]:
oned = np.array((3,4,54,54))
oned

array([ 3,  4, 54, 54])

In [69]:
twod = np.array([[1,2,3,4],[6,7,8,9]])
twod

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [70]:
threed = np.array([[[1,2,3,4],[6,7,8,9]],
                  [[11,12,13,14],[16,17,18,19]]])
threed

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]]])

## check no of dimensions using ndim

ndim

In [71]:
threed.ndim

3

In [72]:
twod.ndim

2

## define the dimension using ndmin

In [77]:
narray = np.array([1,2,3,4], ndmin = 5)
print(narray)
print()

[[[[[1 2 3 4]]]]]



#### hetergenous type 

In [80]:
het = np.array([34,'hey',True, 67])
print(het)

['34' 'hey' 'True' '67']


## Array Indexing

In [91]:
print(oned)

[ 3  4 54 54]


In [92]:
oned[3]

54

In [93]:
oned[-1]

54

In [94]:
oned[1] + oned [2]

58

In [95]:
print(twod)

[[1 2 3 4]
 [6 7 8 9]]


In [97]:
twod[1]

array([6, 7, 8, 9])

In [98]:
twod[0,3]

4

In [99]:
twod[-2]

array([1, 2, 3, 4])

In [101]:
twod[-2,-3]

2

In [102]:
print(threed)

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [16 17 18 19]]]


In [103]:
threed[0]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [104]:
threed[1,0]

array([11, 12, 13, 14])

In [105]:
threed[1,1,3]

19

In [106]:
threed[-2,-1,-3]

7

In [107]:
threed[1,-2]

array([11, 12, 13, 14])

## Array Slicing [start:end:step]

if end is present end-1
else end only

In [108]:
print(oned)

[ 3  4 54 54]


In [109]:
oned[2:]

array([54, 54])

In [110]:
oned[:2]

array([3, 4])

In [111]:
print(twod)

[[1 2 3 4]
 [6 7 8 9]]


In [118]:
# [rows,columns]
twod[1,1:4]

array([7, 8, 9])

In [119]:
twod[0:2, 2]

array([3, 8])

In [120]:
twod[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [121]:
twod[1,2]

8

In [122]:
twod[1:,:2]

array([[6, 7]])

In [123]:
threed

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]]])

In [124]:
# threed[select 0,1,rows,columns]
threed[1, :, 1:3]

array([[12, 13],
       [17, 18]])

In [125]:
threed[0,:1,:1]

array([[1]])

### Data Types:

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [126]:
threed.dtype

dtype('int64')

## create array with defined dtype

In [129]:
d = np.array(['ab','cd'],dtype = 'S')
print(d)

[b'ab' b'cd']


###### convert to specific type using astype()

In [132]:
f = np.array([2.3,4.5,5.6])
i = f.astype(int)
i

array([2, 4, 5])

##### if value cannot be converted
1. astype('i') etc

##### copy() - copies the array and any changes made will not be affected to the original array 
##### view() - copies the array and any changes will affect the original array

In [140]:
arr = np.array([2,3,4,5,6])
arr_1 = arr.copy()
arr[0] = 34
print(arr)
print(arr_1)

[34  3  4  5  6]
[2 3 4 5 6]


In [141]:
arr = np.array([2,3,4,5,6])
arr_1 = arr.view()
arr[0] = 34
print(arr)
print(arr_1)

[34  3  4  5  6]
[34  3  4  5  6]


In [142]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### Array Shape -  shape
shape returns a tuple with each index having the number of corresponding elements.

In [148]:
twod.shape

(2, 4)

In [149]:
threed


array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]]])

In [147]:
threed.shape

(2, 2, 4)

### Array reshaping - reshape()

In [153]:
twod.reshape(4,2)

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

### Array Iterating

In [155]:
for x in oned:
    print(x)

3
4
54
54


In [159]:
for z in threed:
    for y in z:
        for x in y:
            print(x)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


## Joining arrays


In [160]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [168]:
#0 rows, 1 columns
# If axis=0, it would concatenate the arrays along the rows.
# If axis=1, it concatenates along the columns.

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Joining Arrays Using Stack Functions

In [170]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [172]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [173]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [175]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Splitting NumPy Arrays - array_split()

In [182]:
arr = np.array([1, 2, 3, 4, 5, 6])

split = np.array_split(arr,2)
split

[array([1, 2, 3]), array([4, 5, 6])]

In [183]:

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [184]:
# An alternate solution is using hsplit() opposite of hstack() for 2d arrays

In [185]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [186]:
#  Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

## Searching Arrays
Returns index

In [189]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
x

(array([3, 5, 6]),)

In [191]:
# Search Sorted

In [192]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
x

1

In [193]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side ='right')
x

2

In [197]:
# The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Sorting Arrays

In [198]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [199]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [201]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# The example above will return [41, 43], why?

# Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


## Random Numbers in NumPy

In [205]:
from numpy import random
x = random.randint(100)

print(x)

57


In [206]:
x = random.rand()

print(x)

0.9135102954506664


In [207]:
x=random.randint(100, size=(5))

print(x)

[ 0 81 99 28 34]


In [208]:
x = random.randint(100, size=(3, 5))

print(x)

[[67 84  8 32 78]
 [46 21 84 24 12]
 [21  7 93 44 87]]


## Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [209]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [210]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 7 9 7]
 [7 7 9 5 7]
 [5 7 3 9 9]]


In [214]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [217]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [218]:
ones_1d = np.ones(3)
ones_1d

array([1., 1., 1.])

## ufun funcs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.

In [219]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [220]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


## Create Your Own ufunc

In [221]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [222]:
print(type(np.add))

<class 'numpy.ufunc'>


In [223]:
print(type(np.concatenate))

<class 'function'>
